### ISSUE TITLE
0.6.3 fails to build on NetBSD

### ISSUE THREAD

**Issue by 0323pin** [charklie/rsftch#10]
Hi,

0.6.3 fails to build with:
```
   Compiling rsftch v0.6.3 (/usr/pkgsrc/wip/rsftch/work/rsftch-0.6.3)
error[E0308]: mismatched types
   --> src/fns.rs:730:37
    |
730 |             let page_size = sysconf("_SC_PAGESIZE").unwrap_or(4096) as u64;
    |                             ------- ^^^^^^^^^^^^^^ expected `i32`, found `&str`
    |                             |
    |                             arguments to this function are incorrect
    |
note: function defined here
   --> src/fns.rs:772:4
    |
772 | fn sysconf(name: i32) -> Option<i64> {
    |    ^^^^^^^ ---------

For more information about this error, try `rustc --explain E0308`.
error: could not compile `rsftch` (bin "rsftch") due to 1 previous error
*** Error code 101
```

**Comment by 0323pin** [comment]
On a more general note, I've seen the dependency list was updated.

> pciutils
xrandr
glibc

What is this supposed to mean? Does `rsftch` now depends on GNU-libC?

If this is the case, it's unfortunate, none of my systems use GNU-libC. NetBSD has, of course, it's own libC implementation and on Linux, I use musl.

Would you mind commenting?

**Comment by charklie** [comment]
Oh really? The libC dep was an attempt on making it as fast as possible. I could absolutely use another method if you'd prefer it that way, although is there a way to keep it or would it cause issues on NetBSD?

**Comment by 0323pin** [comment]
👀 Something is not right ...

Here's a screenshot on my Void Linux machine,
![2024-05-27-203348_1920x1080_scrot](https://github.com/charklie/rsftch/assets/90570748/78f301a6-71c7-474c-998d-f8d0906b56dd)

How is this even possible? I don't have glibc on that machine, it runs musl.

But, I'm still not able to build 0.6.3 on NetBSD.

**Comment by 0323pin** [comment]
@charklie 

> The libC dep was an attempt on making it as fast as possible.

Ok, I get that but, I guess you are using features that are not specific to GNU-libC, else it wouldn't work on musl-libC.

> is there a way to keep it or would it cause issues on NetBSD?

If the required definitions are available on NetBSD-libC, it should be no problem. But, right now I wouldn't know because, it's failing to build as mentioned in the original post.

```
   Compiling rsftch v0.6.3 (/usr/pkgsrc/wip/rsftch/work/rsftch-0.6.3)
error[E0308]: mismatched types
   --> src/fns.rs:730:37
    |
730 |             let page_size = sysconf("_SC_PAGESIZE").unwrap_or(4096) as u64;
    |                             ------- ^^^^^^^^^^^^^^ expected `i32`, found `&str`
    |                             |
    |                             arguments to this function are incorrect
    |
note: function defined here
   --> src/fns.rs:772:4
    |
772 | fn sysconf(name: i32) -> Option<i64> {
    |    ^^^^^^^ ---------

For more information about this error, try `rustc --explain E0308`.
error: could not compile `rsftch` (bin "rsftch") due to 1 previous error
*** Error code 101
```

**Comment by 0323pin** [comment]
@charklie Obviously, I'm not doing this correctly, see screenshot below. But, the following diff allows the code to compile:
```
--- fns.rs	2024-05-29 13:28:43.073013226 +0200
+++ src/fns.rs	2024-05-29 13:23:35.173037805 +0200
@@ -727,7 +727,7 @@
         {
             let total = hw_physmem.parse::<u64>().unwrap_or(0);
             let free_pages = vm_stats_vm_v_free_count.parse::<u64>().unwrap_or(0);
-            let page_size = sysconf("_SC_PAGESIZE").unwrap_or(4096) as u64;
+            let page_size = sysconf(libc::_SC_PAGESIZE).unwrap_or(4096) as u64;

             let total_bytes = total * page_size;
             let free_bytes = free_pages * page_size;
```

With a warning,
```
warning: function `parse_meminfo_value` is never used
   --> src/fns.rs:748:4
    |
748 | fn parse_meminfo_value(line: &str) -> u64 {
    |    ^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default
```

![2024-05-29-132813_1366x768_scrot](https://github.com/charklie/rsftch/assets/90570748/2215334a-a0d7-4fc7-b3ce-b4c88c24fb4a)

Would you mind having a look?

**Comment by 0323pin** [comment]
Just to add, `_SC_PAGESIZE` is defined in [rust-libc](https://github.com/rust-lang/libc/blob/acc7bb1a38e2b9d6a18f28279d80d464c4c25089/src/unix/bsd/netbsdlike/mod.rs#L577)

**Comment by charklie** [comment]
> @charklie Obviously, I'm not doing this correctly, see screenshot below. But, the following diff allows the code to compile:
> 
> ```
> 
> --- fns.rs	2024-05-29 13:28:43.073013226 +0200
> 
> +++ src/fns.rs	2024-05-29 13:23:35.173037805 +0200
> 
> @@ -727,7 +727,7 @@
> 
>          {
> 
>              let total = hw_physmem.parse::<u64>().unwrap_or(0);
> 
>              let free_pages = vm_stats_vm_v_free_count.parse::<u64>().unwrap_or(0);
> 
> -            let page_size = sysconf("_SC_PAGESIZE").unwrap_or(4096) as u64;
> 
> +            let page_size = sysconf(libc::_SC_PAGESIZE).unwrap_or(4096) as u64;
> 
> 
> 
>              let total_bytes = total * page_size;
> 
>              let free_bytes = free_pages * page_size;
> 
> ```
> 
> 
> 
> With a warning,
> 
> ```
> 
> warning: function `parse_meminfo_value` is never used
> 
>    --> src/fns.rs:748:4
> 
>     |
> 
> 748 | fn parse_meminfo_value(line: &str) -> u64 {
> 
>     |    ^^^^^^^^^^^^^^^^^^^
> 
>     |
> 
>     = note: `#[warn(dead_code)]` on by default
> 
> ```
> 
> 
> 
> ![2024-05-29-132813_1366x768_scrot](https://github.com/charklie/rsftch/assets/90570748/2215334a-a0d7-4fc7-b3ce-b4c88c24fb4a)
> 
> 
> 
> Would you mind having a look?

Well if that works well, can you make it a PR, I'm not at my computer currently and wont be for most likely 2 weeks, thanks.

**Comment by 0323pin** [comment]
> Well if that works well, can you make it a PR

I could do a PR but, it doesn't work well. It allows it to compile and run but, the memory output is _zero of zero_

> I'm not at my computer currently and wont be for most likely 2 weeks, thanks.

That's fine, I can wait.

**Comment by charklie** [comment]
@0323pin Hey, I just pushed a fix that hopefully works, I'll hold off on publishing to crates.io until I know if it does.
Currently working on fixing the GPU info saying "AMD Radeon Radeon".

**Comment by 0323pin** [comment]
Hi, thanks.
I should be able to test this tomorrow.

**Comment by 0323pin** [comment]
@charklie Tested now.

The build works fine, without any warnings, I would say this is fixed and I can update the package.

As for memory usage, it still reads as _zero_ out of _zero_

![2024-06-01-112616_658x734_scrot](https://github.com/charklie/rsftch/assets/90570748/d63fe602-e4c2-4414-84a8-48dfbbb09597)

**Comment by charklie** [comment]
@0323pin Could you run `sysctl -n hw.physmem` and `sysctl -n vm.stats.vm.v_free_count` then screenshot the output for me?

**Comment by 0323pin** [comment]
Yes, of course.

```
~> sysctl -n hw.physmem
-1
```

**Comment by charklie** [comment]
@0323pin Wait, isnt `/proc/meminfo` a thing on NetBSD?

**Comment by 0323pin** [comment]
@charklie Bare with me, we are going into areas where I usually don't look.
Apparently, yes. At least,
```
~> ls /proc | grep mem
.r--r--r-- root    wheel     0 B Sat Jun  1 12:14:07 2024 meminfo
~> vim /proc/meminfo
```
![2024-06-01-121549_1366x768_scrot](https://github.com/charklie/rsftch/assets/90570748/55d5762f-0839-4229-96d7-30e9616a422a)

**Comment by charklie** [comment]
@0323pin Well that makes it much simpler 😆 Then I could just use the method of getting memory as I did on Linux machines.

**Comment by 0323pin** [comment]
Let's try that, than.
Do it on a branch and I'll test it for you.

**Comment by charklie** [comment]
@0323pin Just pushed to branch [meminfo_netbsd](https://github.com/charklie/rsftch/tree/meminfo_netbsd). I forgot to remove the two helper functions (`sysconf` and `sysctl`), so those will be removed in the master commit.

**Comment by 0323pin** [comment]
Just a minute or, two ...

**Comment by 0323pin** [comment]
Alright 🎉 

![2024-06-01-123528_1366x768_scrot](https://github.com/charklie/rsftch/assets/90570748/257b812b-fd8b-4d03-8520-9bb7fb4e8d57)

**Comment by charklie** [comment]
@0323pin Yep, perfect. I'll push to master branch and to crates.io now.

**Comment by 0323pin** [comment]
Thank you for your patience 👍

**Comment by 0323pin** [comment]
0.6.4 [merged](http://mail-index.netbsd.org/pkgsrc-changes/2024/06/01/msg301082.html)

**Comment by charklie** [comment]
Thank you!
