### ISSUE TITLE
[BUG] xrandr panic and failed when used in WSL

### ISSUE THREAD

**Issue by ekarious** [charklie/rsftch#13]
`xrandr was not found.`
Might need to be install on linux side if wanted to be used.

**Comment by charklie** [comment]
Well yeah, xrandr is an xorg implementation, it wont work on a non-linux enviorment, I am workong on making it not panic if xrandr isnt installed though so it should work soon on WSL.

**Comment by charklie** [comment]
Just fixed

**Comment by ekarious** [comment]
Works perfectly in WSL ! 
Thank you

**Comment by charklie** [comment]
Happy to see it working.
