### ISSUE TITLE
[BUG] Missing binaries in v0.6.5 & v0.7.1

### ISSUE THREAD

**Issue by aleksasiriski** [charklie/rsftch#14]
Title

**Comment by charklie** [comment]
Added now 👍

**Comment by aleksasiriski** [comment]
Also [v0.6.0](https://github.com/charklie/rsftch/releases/tag/v0.6.0) if you want to stay consistent :) Consider adding a CI/CD w/ Github Actions for this, it will make life much easier. You can probably just copy paste it from some popular FOSS projects written in Rust like LLDAP, Vaultwarden or Redlib.
