### ISSUE TITLE
GPU readout empty on NetBSD

### ISSUE THREAD

**Issue by 0323pin** [charklie/rsftch#15]
Hi @charklie 

> v0.7.1 Massive rework! 
Release notes:
[...]
Switched to be using the sensors command and regex for CPU temperature, now no longer over reporting

This is bad, as far as I understand this is a **Linux only tool**. Depending on `lm_sensors` kills support for non-Linux systems.

Thoughts?!
Regards

**Comment by charklie** [comment]
> Hi @charklie 
> 
> 
> 
> > v0.7.1 Massive rework! 
> 
> Release notes:
> 
> [...]
> 
> Switched to be using the sensors command and regex for CPU temperature, now no longer over reporting
> 
> 
> 
> This is bad, as far as I understand this is a **Linux only tool**. Depending on `lm_sensors` kills support for non-Linux systems.
> 
> 
> 
> Thoughts?!
> 
> Regards

Oh right! I didn't even think of that, assuming the program still works as expected on NetBSD, I'll fix the README. Thanks!

**Comment by 0323pin** [comment]
Yes, it still builds and works. Although, ...

![2024-08-18-151009_937x519_scrot](https://github.com/user-attachments/assets/f57b3555-9396-4e19-bcc4-63be20563599)

The GPU read-out is empty again and the package count is wrong by "+1". These things were fixed earlier but, I'd guess they slipped through during re-write?!

**Comment by charklie** [comment]
> Yes, it still builds and works. Although, ...
> 
> 
> 
> ![2024-08-18-151009_937x519_scrot](https://github.com/user-attachments/assets/f57b3555-9396-4e19-bcc4-63be20563599)
> 
> 
> 
> The GPU read-out is empty again and the package count is wrong by "+1". These things were fixed earlier but, I'd guess they slipped through during re-write?!

Thats really odd, nothing in the function changed apart from some renaming? The package count should be easy to fix though.

**Comment by 0323pin** [comment]
> Thats really odd, nothing in the function changed apart from some renaming? The package count should be easy to fix though.

I wounder ... is it picking packages manually installed? Or, did you forget to subtract "1" as 
~> ls /usr/pkg/pkgdb | wc -l
191

But one entry is the database itself.

I seems to remember there was an issue with integrated gpu readout earlier.

**Comment by charklie** [comment]
> > Thats really odd, nothing in the function changed apart from some renaming? The package count should be easy to fix though.
> 
> 
> 
> I wounder ... is it picking packages manually installed? Or, did you forget to subtract "1" as 
> 
> ~> ls /usr/pkg/pkgdb | wc -l
> 
> 191
> 
> 
> 
> But one entry is the database itself.
> 
> 
> 
> I seems to remember there was an issue with integrated gpu readout earlier.

I should just be able to minus one and its fine, could you run `lspci -nnk` and screenshot the output correlated to your GPU?

**Comment by 0323pin** [comment]
Sure, I'll get this later today. Just realized memory is also wrong 😞

Used and total show the same value.

OT, unless you are using a VPN (I'm not) we are in the same city 🤣 

Hej på dig!

**Comment by charklie** [comment]
Vad roligt!

**Comment by 0323pin** [comment]
Varsågod,

```
~> lspci -nnk
Usage: lspci [<switches>]

Basic display modes:
-mm		Produce machine-readable output (single -m for an obsolete format)
-t		Show bus tree

Display options:
-v		Be verbose (-vv or -vvv for higher verbosity)
-x		Show hex-dump of the standard part of the config space
-xxx		Show hex-dump of the whole config space (dangerous; root only)
-xxxx		Show hex-dump of the 4096-byte extended config space (root only)
-b		Bus-centric view (addresses and IRQ's as seen by the bus)
-D		Always show domain numbers
-P		Display bridge path in addition to bus and device number
-PP		Display bus path in addition to bus and device number

Resolving of device ID's to names:
-n		Show numeric ID's
-nn		Show both textual and numeric ID's (names & numbers)
-q		Query the PCI ID database for unknown ID's via DNS
-qq		As above, but re-query locally cached entries
-Q		Query the PCI ID database for all ID's via DNS

Selection of devices:
-s [[[[<domain>]:]<bus>]:][<slot>][.[<func>]]	Show only devices in selected slots
-d [<vendor>]:[<device>][:<class>]		Show only devices with specified ID's

Other options:
-i <file>	Use specified ID database instead of /usr/pkg/share/pciutils/pci.ids
-M		Enable `bus mapping' mode (dangerous; root only)

PCI access options:
-A <method>	Use the specified PCI access method (see `-A help' for a list)
-O <par>=<val>	Set PCI access parameter (see `-O help' for a list)
-G		Enable PCI access debugging
-F <file>	Read PCI configuration dump from a given file
```

Bonus :)
```
~> pcictl pci0 list
000:00:0: Intel Core 4G (mobile) Host Bridge, DRAM (host bridge, revision 0x0b)
000:02:0: Intel HD Graphics (GT2) (VGA display, revision 0x0b)
000:03:0: Intel Core 4G (mobile) Mini HD audio (mixed mode multimedia, HD Audio 1.0, revision 0x0b)
000:20:0: Intel Core 4G (mobile) USB xHCI (USB serial bus, xHCI, revision 0x04)
000:22:0: Intel Core 4G (mobile) MEI (miscellaneous communications, revision 0x04)
000:25:0: Intel I218-LM Ethernet Connection (ethernet network, revision 0x04)
000:27:0: Intel Core 4G (mobile) HD Audio (mixed mode multimedia, HD Audio 1.0, revision 0x04)
000:28:0: Intel Core 4G (mobile) PCIe (PCI bridge, revision 0xe4)
000:28:3: Intel Core 4G (mobile) PCIe (PCI bridge, revision 0xe4)
000:29:0: Intel Core 4G (mobile) USB EHCI (USB serial bus, EHCI, revision 0x04)
000:31:0: Intel Core 4G (mobile) LPC (ISA bridge, revision 0x04)
000:31:2: Intel Core 4G (mobile) SATA Controller (AHCI) (SATA mass storage, AHCI 1.0, revision 0x04)
000:31:3: Intel Core 4G (mobile) SMBus (SMBus serial bus, revision 0x04)
002:00:0: Intel Centrino Advanced-N 6205 WiFi (miscellaneous network, revision 0x34)
```

**Comment by charklie** [comment]
Då vet vi problemet! Är `pcictl` förinstallerat på NetBSD eller är den en del av `pciutils`?

**Comment by 0323pin** [comment]
> Då vet vi problemet! Är `pcictl` förinstallerat på NetBSD eller är den en del av `pciutils`?

Det är en del av basen. Så, ja den finns i alla NetBSD system, även i servrar.

```
~> which pcictl
/usr/sbin/pcictl
```

**Comment by charklie** [comment]
@0323pin Borde nu funka, bytte till `pcictl` istället för `lspci`.

**Comment by 0323pin** [comment]
> @0323pin Borde nu funka, bytte till `pcictl` istället för `lspci`.

Tack!

Till vänster 0.6.6, till höger 0.7.2

![2024-08-19-053826_1366x768_scrot](https://github.com/user-attachments/assets/e485cec1-4d8d-4fa7-b9d4-6d5b8c425341)

 - Vet inte riktigt varför `mem` är fel nu, när det fungerade tidigare.

 - Vad det gäller gpu, kanske går att snygga till det.

 - `packs` är fortfarande "+1"

 - Och för info får jag följande varning:
```
   Compiling rsftch v0.7.2 (/home/pin/Downloads/rsftch-0.7.2)
warning: unused import: `regex::Regex`
 --> src/info.rs:2:5
  |
2 | use regex::Regex;
  |     ^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: function `gpu_temp` is never used
  --> src/info.rs:91:4
   |
91 | fn gpu_temp() -> String {
   |    ^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `rsftch` (bin "rsftch") generated 2 warnings (run `cargo fix --bin "rsftch"` to apply 1 suggestion)
    Finished `release` profile [optimized] target(s) in 1m 00s
```

Men detta kanske kommer från "dead code" i NetBSD och syns inte i Linux. Har inte testat i Linux.

**Comment by charklie** [comment]
Pushade ny version till git, alla problem ska vara fixade. Väntar att publicera till cargo tills jag vet att allting funkar som det ska.

**Comment by charklie** [comment]
Kan du skicka en skärmavbild när du kör `cat /dev/kmem`? Tack.

**Comment by 0323pin** [comment]
Ge mig ett par minuter bara :)

**Comment by 0323pin** [comment]
![2024-08-19-143253_1366x768_scrot](https://github.com/user-attachments/assets/b4b7533c-6834-4cc5-a807-3b7888b802d3)

**Comment by charklie** [comment]
Skulle du kunna visa rsftch, `cat /proc/meminfo`'s `MemAvailable` variabel och `top`? Då borde jag kunna se vad jag ska använda för att visa minne.

**Comment by 0323pin** [comment]
Japp ...
![2024-08-19-144336_1366x768_scrot](https://github.com/user-attachments/assets/f80a8ec4-46a4-4914-a5dd-a9040e59be22)

**Comment by 0323pin** [comment]
Säg bara till om du behöver något annat oxå :)

**Comment by charklie** [comment]
Det där borde vara allt som behövs. Vet redan hur jag ska göra!

**Comment by charklie** [comment]
Nu ja! "02:0:" i början av GPU infot ska ha försvunnit, och minne ska inte visa 9.12/9.12
Säg till om det funkar så jag kan publicera till cargo.

**Comment by 0323pin** [comment]
`git pull -r` & building :)

**Comment by charklie** [comment]
Vad hände? Fungerar det?

**Comment by 0323pin** [comment]
Sorry, något dök upp här på jobbet.

Nästan ...

![2024-08-19-154715_1366x768_scrot](https://github.com/user-attachments/assets/28fc8b37-7301-4fc0-a62b-7ac60ae482b6)

**Comment by charklie** [comment]
Ingen fara! Pushade ny version till git nu och publicerar till cargo.

**Comment by 0323pin** [comment]
Tack! Fixar paketet senare idag eller imorgon.

Har dock en fråga ...
I Linux, om jag inte har `lm_sensors` installerade, kommer det att bygga eller är det bara så att en readout inte finns?

**Comment by charklie** [comment]
> Har dock en fråga ... I Linux, om jag inte har `lm_sensors` installerade, kommer det att bygga eller är det bara så att en readout inte finns?

Provade nyss, verkar som att den kommer att panikera på en unwrap, kanske borde fixa detta nästa uppdatering dock.

![image](https://github.com/user-attachments/assets/93fc11cf-dbdd-4cdc-abb5-48a47ffba36f)

**Comment by charklie** [comment]
@0323pin Den bygger dock!

**Comment by 0323pin** [comment]
Ok! Tack.
Så den bygger med spottar ut en _panic_ när den körs.

Tack för testet
