### ISSUE TITLE
GPU Info not showing on NetBSD

### ISSUE THREAD

**Issue by 0323pin** [charklie/rsftch#4]
Hi,

Would you please remove `Cargo.lock` from `.gitignore`.
We (NetBSD) have a script that reads `Cargo.lock` to fetch all dependency crates. When this is not available I need to do it manually.

Thanks!

**Comment by charklie** [comment]
Oh yeah sorry! pushing in 2 minutes.

**Comment by 0323pin** [comment]
Cheers

**Comment by 0323pin** [comment]
@charklie All good thanks! The new looks are nice :+1: 

Would you mind a question, though?

Why is there a gap on the last read-out group, between cpu and memory?
Is this just due to the Intel trademark and font rendering? Just curious, that's all.

![2024-04-02-072723_509x469_scrot](https://github.com/charklie/rsftch/assets/90570748/fc9c788c-c364-4d42-ab0a-77d588b1d50a)

**Comment by charklie** [comment]
@0323pin so it looks like theres an issue with the gpu function... is [pciutils](https://cdn.netbsd.org/pub/pkgsrc/current/pkgsrc/sysutils/pciutils/index.html) installed on your system?

besides that, happy to see you liking the new visuals!

**Comment by 0323pin** [comment]
@charklie Yes, I actually do have it install
```
~> pkgin list | grep pciutils
pciutils-3.11.1      PCI bus manipulation utility similar to NetBSD pcictl(8)
~> ls /usr/pkg/sbin/ | grep lspci
.rwxr-xr-x root wheel 111 KB Sun Feb 25 18:09:06 2024 lspci
~> lspci
00:00.0 Host bridge: Intel Corporation Haswell-ULT DRAM Controller (rev 0b)
00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 0b)
00:03.0 Audio device: Intel Corporation Haswell-ULT HD Audio Controller (rev 0b)
00:14.0 USB controller: Intel Corporation 8 Series USB xHCI HC (rev 04)
00:16.0 Communication controller: Intel Corporation 8 Series HECI #0 (rev 04)
00:19.0 Ethernet controller: Intel Corporation Ethernet Connection I218-LM (rev 04)
00:1b.0 Audio device: Intel Corporation 8 Series HD Audio Controller (rev 04)
00:1c.0 PCI bridge: Intel Corporation 8 Series PCI Express Root Port 1 (rev e4)
00:1c.3 PCI bridge: Intel Corporation 8 Series PCI Express Root Port 4 (rev e4)
00:1d.0 USB controller: Intel Corporation 8 Series USB EHCI #1 (rev 04)
00:1f.0 ISA bridge: Intel Corporation 8 Series LPC Controller (rev 04)
00:1f.2 SATA controller: Intel Corporation 8 Series SATA Controller 1 [AHCI mode] (rev 04)
00:1f.3 SMBus: Intel Corporation 8 Series SMBus Controller (rev 04)
02:00.0 Network controller: Intel Corporation Centrino Advanced-N 6205 [Taylor Peak] (rev 34)
```

You might be interested to know that NetBSD has a native tool too,
```
~> pcictl pci0 list
000:00:0: Intel Core 4G (mobile) Host Bridge, DRAM (host bridge, revision 0x0b)
000:02:0: Intel HD Graphics (GT2) (VGA display, revision 0x0b)
000:03:0: Intel Core 4G (mobile) Mini HD audio (mixed mode multimedia, HD Audio 1.0, revision 0x0b)
000:20:0: Intel Core 4G (mobile) USB xHCI (USB serial bus, xHCI, revision 0x04)
000:22:0: Intel Core 4G (mobile) MEI (miscellaneous communications, revision 0x04)
000:25:0: Intel I218-LM Ethernet Connection (ethernet network, revision 0x04)
000:27:0: Intel Core 4G (mobile) HD Audio (mixed mode multimedia, HD Audio 1.0, revision 0x04)
000:28:0: Intel Core 4G (mobile) PCIe (PCI bridge, revision 0xe4)
000:28:3: Intel Core 4G (mobile) PCIe (PCI bridge, revision 0xe4)
000:29:0: Intel Core 4G (mobile) USB EHCI (USB serial bus, EHCI, revision 0x04)
000:31:0: Intel Core 4G (mobile) LPC (ISA bridge, revision 0x04)
000:31:2: Intel Core 4G (mobile) SATA Controller (AHCI) (SATA mass storage, AHCI 1.0, revision 0x04)
000:31:3: Intel Core 4G (mobile) SMBus (SMBus serial bus, revision 0x04)
002:00:0: Intel Centrino Advanced-N 6205 WiFi (miscellaneous network, revision 0x34)
```

Hope this helps.

**Comment by charklie** [comment]
> @charklie Yes, I actually do have it install
> 
> ```
> ~> pkgin list | grep pciutils
> pciutils-3.11.1      PCI bus manipulation utility similar to NetBSD pcictl(8)
> ~> ls /usr/pkg/sbin/ | grep lspci
> .rwxr-xr-x root wheel 111 KB Sun Feb 25 18:09:06 2024 lspci
> ~> lspci
> 00:00.0 Host bridge: Intel Corporation Haswell-ULT DRAM Controller (rev 0b)
> 00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 0b)
> 00:03.0 Audio device: Intel Corporation Haswell-ULT HD Audio Controller (rev 0b)
> 00:14.0 USB controller: Intel Corporation 8 Series USB xHCI HC (rev 04)
> 00:16.0 Communication controller: Intel Corporation 8 Series HECI #0 (rev 04)
> 00:19.0 Ethernet controller: Intel Corporation Ethernet Connection I218-LM (rev 04)
> 00:1b.0 Audio device: Intel Corporation 8 Series HD Audio Controller (rev 04)
> 00:1c.0 PCI bridge: Intel Corporation 8 Series PCI Express Root Port 1 (rev e4)
> 00:1c.3 PCI bridge: Intel Corporation 8 Series PCI Express Root Port 4 (rev e4)
> 00:1d.0 USB controller: Intel Corporation 8 Series USB EHCI #1 (rev 04)
> 00:1f.0 ISA bridge: Intel Corporation 8 Series LPC Controller (rev 04)
> 00:1f.2 SATA controller: Intel Corporation 8 Series SATA Controller 1 [AHCI mode] (rev 04)
> 00:1f.3 SMBus: Intel Corporation 8 Series SMBus Controller (rev 04)
> 02:00.0 Network controller: Intel Corporation Centrino Advanced-N 6205 [Taylor Peak] (rev 34)
> ```
> 
> You might be interested to know that NetBSD has a native tool too,
> 
> ```
> ~> pcictl pci0 list
> 000:00:0: Intel Core 4G (mobile) Host Bridge, DRAM (host bridge, revision 0x0b)
> 000:02:0: Intel HD Graphics (GT2) (VGA display, revision 0x0b)
> 000:03:0: Intel Core 4G (mobile) Mini HD audio (mixed mode multimedia, HD Audio 1.0, revision 0x0b)
> 000:20:0: Intel Core 4G (mobile) USB xHCI (USB serial bus, xHCI, revision 0x04)
> 000:22:0: Intel Core 4G (mobile) MEI (miscellaneous communications, revision 0x04)
> 000:25:0: Intel I218-LM Ethernet Connection (ethernet network, revision 0x04)
> 000:27:0: Intel Core 4G (mobile) HD Audio (mixed mode multimedia, HD Audio 1.0, revision 0x04)
> 000:28:0: Intel Core 4G (mobile) PCIe (PCI bridge, revision 0xe4)
> 000:28:3: Intel Core 4G (mobile) PCIe (PCI bridge, revision 0xe4)
> 000:29:0: Intel Core 4G (mobile) USB EHCI (USB serial bus, EHCI, revision 0x04)
> 000:31:0: Intel Core 4G (mobile) LPC (ISA bridge, revision 0x04)
> 000:31:2: Intel Core 4G (mobile) SATA Controller (AHCI) (SATA mass storage, AHCI 1.0, revision 0x04)
> 000:31:3: Intel Core 4G (mobile) SMBus (SMBus serial bus, revision 0x04)
> 002:00:0: Intel Centrino Advanced-N 6205 WiFi (miscellaneous network, revision 0x34)
> ```
> 
> Hope this helps.

Hello, I just remembered that initially, I was planning that if the user has integrated graphics, it would simply not return anything but I forgot completely of that. As I'm sending this message, I'm changing up some of the variable declaration and such by changing to hashmaps (which will hopefully speed it up a teeny tiny bit) and the feature I forgot about will be a thing.

Thank you!

**Comment by 0323pin** [comment]
Nice, in the meantime I'm pushing the update to 0.3.7

**Comment by charklie** [comment]
> Nice, in the meantime I'm pushing the update to 0.3.7

Great! Thank you so much btw for hosting it on pkgsrc

**Comment by 0323pin** [comment]
No worries 😀
