### ISSUE TITLE
v0.4.1 unavailable

### ISSUE THREAD

**Issue by 0323pin** [charklie/rsftch#5]
Hi,

Just tried to update to 0.4.1 but, it's not available.

![2024-04-11-175449_1366x768_scrot](https://github.com/charklie/rsftch/assets/90570748/fbe9d18a-1f9b-4b6b-a9a4-ce230ddddd5d)

I know what to do to build it but, it would be nice it it was published so I don't get:
```
=> Fetching rsftch-0.4.1.crate
Trying [2a04:4e42:14::649]:443 ...
ftp: Can't connect to `2a04:4e42:14::649:443': No route to host
Trying 151.101.86.137:443 ...
Requesting https://static.crates.io/crates/rsftch/rsftch-0.4.1.crate
ftp: Error retrieving file `403'
fetch: Unable to fetch expected file rsftch-0.4.1.crate
Trying [2a04:4e42:14::262]:443 ...
ftp: Can't connect to `2a04:4e42:14::262:443': No route to host
Trying 151.101.85.6:443 ...
Requesting https://cdn.NetBSD.org/pub/pkgsrc/distfiles/rsftch-0.4.1.crate
ftp: Error retrieving file `404 Not Found'
fetch: Unable to fetch expected file rsftch-0.4.1.crate
Trying [2001:660:3302:282a:204:75ff:fe9f:9e11]:80 ...
ftp: Can't connect to `2001:660:3302:282a:204:75ff:fe9f:9e11:80': No route to host
Trying 132.227.74.11:80 ...
Requesting http://ftp.fr.NetBSD.org/pub/pkgsrc/distfiles/rsftch-0.4.1.crate
ftp: Error retrieving file `404 Not Found'
fetch: Unable to fetch expected file rsftch-0.4.1.crate
Trying [2001:470:a085:999::21]:443 ...
ftp: Can't connect to `2001:470:a085:999::21:443': No route to host
Trying 199.233.217.201:443 ...
Requesting https://ftp.NetBSD.org/pub/pkgsrc/distfiles/rsftch-0.4.1.crate
ftp: Error retrieving file `404 Not Found'
fetch: Unable to fetch expected file rsftch-0.4.1.crate
*** Error code 1

Stop.
```

😉

**Comment by charklie** [comment]
Whoopsies, I finished making 0.4 last night at like 4 am so I guess I was a bit tired and forgot to publish it to crates.io...

Fixed now.

**Comment by 0323pin** [comment]
Thank you!

> ... last night at like 4 am ...

You mean really early morning 🤣 
I usually go up at 5 am.

**Comment by charklie** [comment]
I usually get up at more like 5 pm 😂

**Comment by 0323pin** [comment]
[Merged](http://mail-index.netbsd.org/pkgsrc-changes/2024/04/11/msg296862.html)

**Comment by charklie** [comment]
@0323pin Great!

Btw, if you have time, is there anyway you could submit rsftch to [awesome-fetch](https://github.com/beucismis/awesome-fetch) since you aren't supposed submit your own?
I'd greatly appreciate it.

**Comment by 0323pin** [comment]
Sure, NP. I'll do it tomorrow.
Cross-platform or, just unix-like?

**Comment by charklie** [comment]
> Sure, NP. I'll do it tomorrow. Cross-platform or, just unix-like?

I'd put it under unix-like since of bsd support.
Thank you!
