### ISSUE TITLE
v0.5.1 panics without the new xrandr local dependency, local configs are on by default which panic, and ASCII formatting is off

### ISSUE THREAD

**Issue by siris** [charklie/rsftch#8]
Summary
========

### First Panic 
Hi @charklie, I just installed `v0.5.1` on Funtoo Linux and it looks like there is an panic error if xrandr is not found due to this code:

https://github.com/charklie/rsftch/blob/95387239b7637500125a29eb7650ffc778aeba9b/src/fns.rs#L418-L422

Not all Linux distribution running `rsftch` are going to have `xrandr` installed by default. Here is the panic:
Rust backtrace:
```
RUST_BACKTRACE=1 rsftch
thread 'main' panicked at /home/ss/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rsftch-0.5.1/src/fns.rs:422:10:
Failed to execute xrandr command: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: rsftch::fns::get_res
   4: rsftch::info
   5: rsftch::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

`Command::new` will complain like this when it can't find the command its invoking.. One way to solve this is to ensure a suite of dependency checks are ran before any function is invoke and then the cleanly bubble up the Rust Error with an Result into the main function with `?`, then in your top-level CLI catch that error, and exit with the the appropriate process code. The [anyhow crate](https://crates.io/crates/anyhow) is very helpful here to easily add better error handling with too much additional code\

### Second Panic

After installing `xrandr` resolve the first panic, I hit another panic:

```
RUST_BACKTRACE=1 rsftch
thread 'main' panicked at /home/ss/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rsftch-0.5.1/src/color_config.rs:75:78:
called `Result::unwrap()` on an `Err` value: "Error opening file: No such file or directory (os error 2)"
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: rsftch::color_config::get_color_config
   4: rsftch::info
   5: rsftch::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Attempting to ignore configs and use a built-in default still doesn't work:
```
rsftch --ignore-color-config
thread 'main' panicked at /home/ss/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rsftch-0.5.1/src/color_config.rs:75:78:
called `Result::unwrap()` on an `Err` value: "Error opening file: No such file or directory (os error 2)"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

These configs should not be required for a default execution and/or `rsftch` should provide some facility to generate them with default settings, or else `rsftch` is broken entirely from default execution if these configs don't work.

### Formatting issues

I am also seeing formatting issues on the ASCII, see screenshot in workaround section

Reproduction Steps
====

* Ensure `xrandr` doesn't exist on your Linux OS or remove it from your shell `PATH`:
```
 which xrandr &>/dev/null ; echo $?
1
```
* `cargo install rsftch` to install version 0.5.1
* Run `rsftch` in a terminal
* Rust Panic should happen
* Install `xrandr` and re-run `rsftch`
* Second Rust Panic should happen

Workaround
=====

1. Install the `x11-apps/xrandr` package in Funtoo Linux and re-run `rsftch` but `rsftch` panics again
2. Manually create some `rsftch` configs `~/.config/rsftch/info.json` and `~/.config/rsftch/colors.json` using `README.md` examples
3. Run `rsftch`
![shot-2024-05-06_12-52-04](https://github.com/charklie/rsftch/assets/700847/8f57fc01-e213-4c89-a026-d751ef5c1748)

**Comment by charklie** [comment]
@siris Hello, I do have default fallback configurations and they work just fine on my machine. I just fixed the ascii formatting via commit. Although I'm unsure why xrandr is failing.

Currently not at my computer but first thing tomorrow when I get a chance I'll try and fix it.

**Comment by siris** [comment]
@charklie thanks, I tested the ASCII hot fix for Funtoo based off the HEAD commit and it works fine :+1: 

The panic for configs occurs when there are not configs in `~/.config/rsftch/` and the `--ignore-config`, `--ignore-color-config`, and `--ignore-info-config` option flags do not appear to work when `~/.config/rsftch/`` doesn't exist. My testing is detailed below:
```
mv -v ~/.config/rsftch /tmp/
created directory '/tmp/rsftch'
copied '/home/ss/.config/rsftch/colors.json' -> '/tmp/rsftch/colors.json'
copied '/home/ss/.config/rsftch/info.json' -> '/tmp/rsftch/info.json'
removed '/home/ss/.config/rsftch/info.json'
removed '/home/ss/.config/rsftch/colors.json'
removed directory '/home/ss/.config/rsftch'

time ./target/debug/rsftch --ignore-color-config
thread 'main' panicked at src/color_config.rs:75:78:
called `Result::unwrap()` on an `Err` value: "Error opening file: No such file or directory (os error 2)"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

time ./target/debug/rsftch --ignore-color-config --ignore-color-config
thread 'main' panicked at src/color_config.rs:75:78:
called `Result::unwrap()` on an `Err` value: "Error opening file: No such file or directory (os error 2)"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

time ./target/debug/rsftch --ignore-color-config
thread 'main' panicked at src/color_config.rs:75:78:
called `Result::unwrap()` on an `Err` value: "Error opening file: No such file or directory (os error 2)"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by charklie** [comment]
> @charklie thanks, I tested the ASCII hot fix for Funtoo based off the HEAD commit and it works fine 👍
> 
> The panic for configs occurs when there are not configs in `~/.config/rsftch/` and the `--ignore-config`, `--ignore-color-config`, and `--ignore-info-config` option flags do not appear to work when `~/.config/rsftch/`` doesn't exist. My testing is detailed below:
> 
> ```
> mv -v ~/.config/rsftch /tmp/
> created directory '/tmp/rsftch'
> copied '/home/ss/.config/rsftch/colors.json' -> '/tmp/rsftch/colors.json'
> copied '/home/ss/.config/rsftch/info.json' -> '/tmp/rsftch/info.json'
> removed '/home/ss/.config/rsftch/info.json'
> removed '/home/ss/.config/rsftch/colors.json'
> removed directory '/home/ss/.config/rsftch'
> 
> time ./target/debug/rsftch --ignore-color-config
> thread 'main' panicked at src/color_config.rs:75:78:
> called `Result::unwrap()` on an `Err` value: "Error opening file: No such file or directory (os error 2)"
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> time ./target/debug/rsftch --ignore-color-config --ignore-color-config
> thread 'main' panicked at src/color_config.rs:75:78:
> called `Result::unwrap()` on an `Err` value: "Error opening file: No such file or directory (os error 2)"
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> time ./target/debug/rsftch --ignore-color-config
> thread 'main' panicked at src/color_config.rs:75:78:
> called `Result::unwrap()` on an `Err` value: "Error opening file: No such file or directory (os error 2)"
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

@siris Just pushed 0.5.2 to github, let me know if it works for you.
The failiure of loading the fallback files actually made me rewrite the `get_color_config()` function and it's much cleaner now, so in a sense it was good it didn't work.

**Comment by siris** [comment]
Thanks @charklie will do integration testing with v0.5.2 on Funtoo Linux later today.

**Comment by charklie** [comment]
@siris Just published to cargo.

**Comment by siris** [comment]
> @siris Just published to cargo.

Just tested the latest v0.5.2 on Funtoo Linux and it works perfectly with no additional configs with zero panics:

![shot-2024-05-08_08-36-44](https://github.com/charklie/rsftch/assets/700847/2cf62e26-8cfb-4a73-8e1e-cc1774cccf34)

Performance is nice as well:

```
hyperfine -w 5 -M 15 rsftch
Benchmark 1: rsftch
  Time (mean ± σ):     123.0 ms ±   7.3 ms    [User: 96.5 ms, System: 21.0 ms]
  Range (min … max):   114.9 ms … 133.6 ms    15 runs
```

That is a 6X speed improvement over my initial tests I did in #7! Very nice.

@charklie I will now start the process of getting `rsftch` packaged up in Funtoo Linux. The only thing we need are git tags or GitHub Releases on the repo tracking the latest version. I will open additional issues for this and other Rust related enhancements. Thanks for all the improvements and `rsftch` Rust code base is evolving nicely :rocket: :tada: :crab:
